
name: deploy CI

on:
  push:
    branches: [ "master", "tobiasarens-patch-1"]
  pull_request:
    branches: [ "master" ]

jobs:
    
  deploy_job:
    environment: production
    runs-on: ubuntu-latest
    container: node:lts-alpine
    steps:
      - run: apk add --no-cache openssh rsync
      - uses: actions/checkout@v4
      # Make sure the @v0.9.0 matches the current version of the action
      - uses: webfactory/ssh-agent@v0.10.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ssh-keyscan "${{ vars.WEBSITE_HOSTNAME }}" >> ~/.ssh/known_hosts
      - run: npm ci
      - run: npm run build
      - run: rsync -vrzO dist/ deploy@${{ vars.WEBSITE_HOSTNAME }}:${{ vars.WEBSITE_PATH }}
