
name: deploy CI

on:
  push:
    branches: [ "master", "tobiasarens-patch-1"]
  pull_request:
    branches: [ "master" ]

jobs:
    
  deploy_job:
    environment: production
    runs-on: ubuntu-latest
    container: node:lts-alpine
    steps:
      - run: apk add --no-cache openssh rsync
      
      - uses: actions/checkout@v6
      - run: npm ci
      - run: npm run build
      
      - name: rsync deployments
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -vzrO 
          path: dist/
          remote_path: ${{ vars.WEBSITE_PATH }}
          remote_host: ${{ vars.WEBSITE_HOSTNAME }} 
          remote_user: deploy
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      #- uses: actions/checkout@v4
      # Make sure the @v0.9.0 matches the current version of the action
      #- uses: webfactory/ssh-agent@v0.10.0
       # with:
       #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #-run: ssh-keyscan ${{ vars.WEBSITE_HOSTNAME }} >> ~/.ssh/known_hosts
      #- run: rsync -vrzO dist/ deploy@${{ vars.WEBSITE_HOSTNAME }}:${{ vars.WEBSITE_PATH }}
